feat: add project aliases config
juraj-hrivnak/Pakku pull request #34
Opened 2024-10-06 03:00 UTC by SettingDust

fix #33
fix #12

2024-10-07 19:48 UTC, juraj-hrivnak requested changes
A project should inherit the `alias` &/or `aliases` from the ProjectConfig.

See [here](https://github.com/juraj-hrivnak/Pakku/blob/main/src/commonMain/kotlin/teksturepako/pakku/api/projects/Project.kt#L184).

2024-10-07 19:49 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/LockFile.kt
> +    }
Unnecessary with config inheritance.

2024-10-07 19:50 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/cli/cmd/Add.kt
> +                            )
Also unnecessary with config inheritance.

2024-10-08 00:35 UTC, SettingDust commented on src/commonMain/kotlin/teksturepako/pakku/cli/cmd/Add.kt
> +                            )
My IDEA is formatting it. Can you provide your `.editorconfig` by export it from IDEA?

2024-10-08 02:11 UTC, SettingDust commented on src/commonMain/kotlin/teksturepako/pakku/cli/cmd/Cfg.kt
> +        "-pa", "--project-alias",
It's working XD. But I will remove this

2024-10-08 07:16 UTC, juraj-hrivnak requested changes

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/ConfigFile.kt
> +    private val serverOverrides: MutableList<String> = mutableListOf(),
Serial name is missing

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/ConfigFile.kt
> +    private val clientOverrides: MutableList<String> = mutableListOf(),
Same here

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/ConfigFile.kt
> +    val projectAliases: MutableMap<String, String> = mutableMapOf()
This shouldn't be needed anymore

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/ConfigFile.kt
> +        var updateStrategy: UpdateStrategy? = null,
Missing serial name

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/ConfigFile.kt
> +        var aliases :MutableSet<String>? = null
Formating: `var aliases: MutableSet<String>? = null`

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/data/Json.kt
> +import kotlinx.serialization.json.JsonNamingStrategy
Unused import

2024-10-08 07:16 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/projects/Project.kt
> +    var aliases: MutableSet<String> = mutableSetOf(),
Should be nullable and null by default.

2024-10-08 07:55 UTC, juraj-hrivnak approved these changes
Great job! Thanks!

2024-10-08 10:31 UTC, merged