feat: allow replace project version with `add`
juraj-hrivnak/Pakku pull request #40
Opened 2024-10-09 01:35 UTC by SettingDust

![图片](https://github.com/user-attachments/assets/9f819c0d-c083-49b8-9f04-aef1532a70e1)

close #38

2024-10-09 13:10 UTC, juraj-hrivnak requested changes

2024-10-09 13:10 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/actions/Addition.kt
> +import teksturepako.pakku.cli.ui.pSuccess
Unused imports

2024-10-09 13:10 UTC, juraj-hrivnak commented on src/commonMain/kotlin/teksturepako/pakku/api/actions/Addition.kt
> +}
Missing empty line on end

2024-10-10 12:31 UTC, juraj-hrivnak commented
I appreciate this, but I ended up implementing it differently in 7b79226cbe008792cea33611d786344a27a7ddc2

2024-10-10 12:31 UTC, closed without merging

2024-10-10 12:37 UTC, SettingDust commented
There is a bug anyway https://github.com/juraj-hrivnak/Pakku/pull/40/commits/1b9a4e15065f57300e15afcf17f508d4def2f2d7